<?php
define("LOG_ON_FAILED","Sorry, but I can't log you on");
define("DIRECT_LINK","You may have got to this page in error.
<br>If you wanted to be somewhere else then please press the Back button
<br>If this is where you wanted to be then please press one of the buttons.");
define("LOG_ON_TO_DELETE","You need to be logged on before you can delete a person.");
define("BLANK_GNAME","The given name cannot be blank");
define("NUMBER_IN_GNAME","The given name cannot include a number");
define("NUMBER_IN_FNAME","The family name cannot include a number");
define("NO_MATCH","There was no match for your search: "); // append the search variable to the end of this message
?>